### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by dengshuaix** [odoo/documentation-user#790] opened 2020-11-16 15:32 UTC
>Hi, have you ever tried to install latex and its dependencies first? It turns out that sphinx calls some latex dependencies to generate PDF.

Can you paste the configuration easily?

**Comment by AntoineVDV** [comment] 2020-11-18 09:10
Hello,

I'm closing this as it is a duplicate of #289.

**Closed by AntoineVDV** 2020-11-18 09:10 UTC
